language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev
      - linux-libc-dev:i386

env:
  global:
    # BBPASS
    - secure: "Aci6ax5j6CdDbWL84yqUY8BlsF4jKqYoFIIw+1yE/4w9Gm6aElurXnTkPtdAnKLlDAYmgs9L/YKdEThfMLEM617ue0tS3QvFFBpLH5k1LiGUYlTKY/oVfXirHYwE0Xd/1hE5P2HKjCokXlhCtYRPOjAKWQWXyYzzzL0dMU4mtzZ08H4aA16s3vS6N7oAQHdKx/CE9ThYj/6I+fQnWQJXTNJd92nf3A0IbRoUMEuZDscnhYJBWE8naZscCe8SnUEseqwTF1u/8viXy1PXf1fBKaPVck0ezMS4yPFpgXQzx8xd3Io5XIRM/GnkPB5IuwUiruO+yR9EHirTncxotE3/Eh72nLqo7He+K38JyfLWwFFErCAVivnFuWyD0xqlzeg9U6he5jzD314d4qLsDpzAOrQ0UyahBerAdoBdcHQXhjRRepLODEbVx8bnB6m1DqPUOQrbNDTCBi9IWudMGk0IqOGSlO96Ts/oTHxkMUmmP0X8TiP4ZriaGCswWdWr8cZ+jTU2Chg05N1Csvwh8AwWEyuWpu3qtwgMRXup/Ymkkg4wyW15BHEkxi0zkVfq5of8psZQ6SRYGGgWjXm5+3V0z/zM4gE7kCi090UZ692WvcordLH6+EW0FplhwswYmfvxxZhzXFcNJ1T71Xq2RAgOj/otMW0h1SQAa6rav82yaVM="

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      env:
        - BUILD_LINUX32=yes
    - os: linux
      compiler: gcc-4.8
      env:
        - BUILD_LINUX32=no

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - curl https://bitbucket.org/Swyter/bitbucket-curl-upload-to-repo-downloads/raw/default/upload-to-bitbucket.sh -O -J && chmod +x ./upload-to-bitbucket.sh

script:
  - git clone --branch hdf5_1_8_18 https://bitbucket.hdfgroup.org/scm/hdffv/hdf5.git hdf5_1_8_18
  - cd hdf5_1_8_18
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]] && [[ "$BUILD_LINUX32" == "yes" ]]; then ./configure --quiet --enable-shared --enable-production=yes --enable-debug=no --disable-deprecated-symbols --disable-hl --with-pic --with-default-api-version=v18 --build=i686-pc-linux-gnu CFLAGS="-w -msse2 -m32" LDFLAGS="-m32"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]] && [[ "$BUILD_LINUX32" == "no" ]]; then ./configure --quiet --enable-shared --enable-production=yes --enable-debug=no --disable-deprecated-symbols --disable-hl --with-pic --with-default-api-version=v18 CFLAGS="-w"; fi
  - make install -C src
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]] && [[ "$BUILD_LINUX32" == "yes" ]]; then tar cJf hdf5-1.8.18_linux32.tar.xz hdf5/include/* hdf5/lib/* src/H5lib_settings.c src/H5Tinit.c src/H5config.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]] && [[ "$BUILD_LINUX32" == "no" ]]; then tar cJf hdf5-1.8.18_linux64.tar.xz hdf5/include/* hdf5/lib/* src/H5lib_settings.c src/H5Tinit.c src/H5config.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]] && [[ "$BUILD_LINUX32" == "yes" ]]; then sh ../upload-to-bitbucket.sh tbeu $BBPASS /tbeu/downloads/downloads hdf5-1.8.18_linux32.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]] && [[ "$BUILD_LINUX32" == "no" ]]; then sh ../upload-to-bitbucket.sh tbeu $BBPASS /tbeu/downloads/downloads hdf5-1.8.18_linux64.tar.xz; fi

notifications:
  email: false

sudo: false
