language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev
      - linux-libc-dev:i386

env:
  global:
    # BBTOKEN
    - secure: "Ac7KY0WGgf2FVYmDpWx34i9U9YtRmq4dsK0QYoA1nwwCgolN2MpvqcSzV1iUcYntQ11YqwuLZ5BsLoEsDA3qKDTqprfEubXdMXVejP/6r6kW+L0gTwhwKqr+GxfKAun2xAr0WEMm90BYGK52L39p4rLGGkL1GhlZE2N+2870hv+F+FB7rQhDlx59aVsUu5FTboBlLBupWg45llDsgU8LV07T/RB5ha/EsggHHOb/2yFq/rW2fTV+61niphTvqYlno6ZODOo8L8QVC//oykIJR8VXFyTPtW7/fbdDvtkWzBlQO37iMwy3KovABvoc8CYsRvkj5pJmJy7to8m/0aCNsmahqgec1s5Bav5lku0RIgJfhD7tF5oUHwfv+m9bcXMWgAgUU4o/4XrJ5363JrEk4sz39h+SjaMVLS2uFm/eFqbwo/KvaDb9FCFYna42FNfauo9zAOwZQz1fldSSP3e4n7RnlIbyMrDmbCsCdJuClocQqKR6QUKRca/jmr28xAhM4zPdKapKh7DCMQJMzecXlj1T+d3/AGtRyu+ShG0QL8L/41Ac3uo3xtDdFq45g/gh1yRdmUHlwizECUMfv4Gi8wQdT/ay52edZWcUJFJONgFRkiAymAQDkxqQG93lYP7PJyUPgXZTJ5Oh+53zGEyWuqTfIvXgcUiV0O3xVa4VpOc="

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      env:
        - PLATFORM=32
    - os: linux
      compiler: gcc-4.8
      env:
        - PLATFORM=64

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - git clone --depth 1 https://github.com/madler/zlib
  - cd zlib
  - if [[ "$PLATFORM" == "32" ]]; then CFLAGS="-w -msse2 -m32" LDFLAGS="-m32" ./configure --prefix=$TRAVIS_BUILD_DIR/zlib --eprefix=$TRAVIS_BUILD_DIR/zlib; fi
  - if [[ "$PLATFORM" == "64" ]]; then ./configure --prefix=$TRAVIS_BUILD_DIR/zlib --eprefix=$TRAVIS_BUILD_DIR/zlib; fi
  - make install
  - cd $TRAVIS_BUILD_DIR

script:
  - git clone --depth 1 --branch hdf5-1_8_23 https://github.com/HDFGroup/hdf5.git hdf5-1_8_23
  - cd hdf5-1_8_23
  - if [[ "$PLATFORM" == "32" ]]; then ./configure --quiet --enable-shared --enable-production=yes --enable-debug=no --disable-deprecated-symbols --disable-hl --with-pic --with-default-api-version=v18 --with-zlib=$TRAVIS_BUILD_DIR/zlib --build=i686-pc-linux-gnu CFLAGS="-w -msse2 -m32" LDFLAGS="-m32"; fi
  - if [[ "$PLATFORM" == "64" ]]; then ./configure --quiet --enable-shared --enable-production=yes --enable-debug=no --disable-deprecated-symbols --disable-hl --with-pic --with-default-api-version=v18 --with-zlib=$TRAVIS_BUILD_DIR/zlib CFLAGS="-w"; fi
  - make install -C src
  - tar cJf hdf5-1.8.23_linux$PLATFORM.tar.xz hdf5/include/* hdf5/lib/* src/H5lib_settings.c src/H5Tinit.c src/H5config.h
  - 'curl -X POST -H "Authorization: Bearer $BBTOKEN" https://api.bitbucket.org/2.0/repositories/tbeu/downloads/downloads -F files=@hdf5-1.8.23_linux$PLATFORM.tar.xz'

notifications:
  email: false
